name: txmatching
channels:
  - conda-forge
dependencies:
  - autopep8=1.6.0
  - bcrypt=3.2.0
  - blinker=1.4
  - dacite==1.6.0
  - flask=2.0.3
  - flask-restx==0.5.1
  - flask-sqlalchemy=2.5.1
  - graph-tool=2.44
  - gunicorn=20.1.0
  - jinja2==3.0.3
  - networkx==2.7.1
  - numpy=1.22.3
  - openpyxl=3.0.10
  - pandas=1.4.2
  - pip=21.2.4
  - pre-commit==2.19.0
  - pyjwt==2.4.0
  - pylint=2.12.2
  - pyotp=2.6.0
  - python=3.10.5
  - requests=2.26.0
  - responses=0.13.3
  - scipy=1.7.3
  - sentry-sdk[flask]==1.6.0
  - sqlalchemy=1.4.32
  - Werkzeug=2.0.3
  - xlrd=2.0.1
  - xlsxwriter=3.0.3
  - pip:
      - Bcrypt-Flask==1.0.2
      - mip==1.14.0
      - openapi-spec-validator==0.4.0
      - pdfkit==1.0.0
      - psycopg2-binary==2.9.3
      - pylint-flask==0.6
      - pylint-flask-sqlalchemy==0.2.0
      - pylint-plugin-utils==0.7
      - swagger-unittest==0.3.4
      - yoyo-migrations==7.3.2
