name: txmatching
channels:
  - conda-forge
dependencies:
  - bcrypt=3.2.0
  - python=3.8.3
  - pip=20.1.1
  - graph-tool=2.33
  - pandas=1.1.1
  - scipy=1.5.2
  - numpy=1.19.1
  - xlrd=1.2.0
  - flask=1.1.2
  - gunicorn=20.0.4
  - flask-sqlalchemy=2.4.4
  - pylint=2.6.0
  - pip:
      - psycopg2-binary==2.8.5
      - pylint-flask==0.6
      - pylint-flask-sqlalchemy==0.2.0
      - pylint-plugin-utils==0.6
      - pre-commit==2.7.1
      - flask_restx==0.2.0
      - flask_bcrypt==0.7.1
      - pyjwt==1.7.1
      - dacite==1.5.1
      - autopep8==1.5.4
