name: txmatching
channels:
  - conda-forge
dependencies:
  - autopep8=1.5.7
  - bcrypt=3.2.0
  - blinker=1.4
  - dacite==1.6.0
  - flask-restx==0.5.0
  - flask-sqlalchemy=2.5.1
  - flask=2.0.1
  - gunicorn=20.1.0
  - jinja2==3.0.1
  - networkx==2.6.2
  - numpy=1.21.2
  - openpyxl=3.0.7
  - pandas=1.3.2
  - pip=20.1.1
  - pre-commit==2.14.1
  - pyjwt==2.0.1
  - pylint=2.10.2
  - pyotp=2.6.0
  - python=3.8.10
  - requests=2.26.0
  - responses=0.13.4
  - scipy=1.7.1
  - sentry-sdk[flask]==1.5.8
  - sqlalchemy=1.4.23
  - Werkzeug=2.0.3
  - xlrd=2.0.1
  - xlsxwriter=3.0.1
  - pip:
      - Bcrypt-Flask==1.0.2
      - mip==1.13.0
      - openapi-spec-validator==0.2.9
      - pdfkit==0.6.1
      - psycopg2-binary==2.9.1
      - pylint-flask-sqlalchemy==0.2.0
      - pylint-flask==0.6
      - pylint-plugin-utils==0.6
      - swagger-unittest==0.3.4
      - yoyo-migrations==7.3.2
