name: txmatching
channels:
  - conda-forge
dependencies:
  - autopep8=2.0.0
  - bcrypt=3.2.2
  - blinker=1.5
  - dacite==1.6.0
  - flask=2.2.2
  - flask-sqlalchemy=2.5.1
  - graph-tool=2.45
  - gunicorn=20.1.0
  - jinja2==3.1.2
  - networkx==2.8.8
  - numpy=1.23.4
  - openpyxl=3.0.10
  - pandas=1.5.1
  - pip=22.3.1
  - pre-commit==2.20.0
  - pyjwt==2.6.0
  - pylint=2.15.5
  - pyotp=2.6.0
  - python=3.11.0
  - requests=2.28.1
  - responses=0.21.0
  - scipy=1.9.3
  - sentry-sdk[flask]==1.10.1
  - sqlalchemy=1.4.43
  - Werkzeug=2.2.2
  - xlrd=2.0.1
  - xlsxwriter=3.0.3
  - pip:
      - Bcrypt-Flask==1.0.2
      - mip==1.14.0
      - openapi-spec-validator==0.4.0
      - pdfkit==1.0.0
      - psycopg2-binary==2.9.5
      - pylint-flask==0.6
      - pylint-flask-sqlalchemy==0.2.0
      - pylint-plugin-utils==0.7
      - swagger-unittest==0.3.6
      - yoyo-migrations==7.3.2
      - flask-restx==1.0.5
