GET https://txmatching.ikem.cz/v1/service/status
Content-Type: application/json

###

###

POST https://txmatching.ikem.cz/v1/user/login
Content-Type: application/json

{
  "email": "mild_service",
  "password": ""
}

> {% client.global.set("auth_token", response.body["auth_token"]); %}
###


PUT https://txmatching.ikem.cz/v1/txm-event/patients
Authorization: Bearer {{auth_token}}
Content-Type: application/json


< /home/honza/IdeaProjects/wien_export.json
//{
//  "country": "AUT",
//  "txm_event_name": "test33",
//  "donors": [],
//  "recipients": []
//}
