# test the api works

GET {{url}}/v1/service/version
Content-Type: application/json


# The workflow below has endpoints that add a user, change or reset password and call recompute endpoint
###

POST {{url}}/v1/user/login
Content-Type: application/json

{
  "email": "t@t.cz",
  "password": "bagr"
}

> {% client.global.set("auth_token", response.body["auth_token"]); %}

###


POST {{url}}/v1/user/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {% client.global.set("auth_token", response.body["auth_token"]); %}
###

POST {{url}}/v1/user/otp
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "otp": ""
}

> {% client.global.set("auth_token", response.body["auth_token"]); %}
###


POST {{url}}/v1/user/register
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "email": "t@t.cz",
  "password": "aa",
  "role": "VIEWER",
  "second_factor": "+420602322527",
  "allowed_countries": [
    "AUT",
    "CZE",
    "ISR"
  ]
}
###

GET {{url}}/v1/user/t@t.cz/reset-password-token
Content-Type: application/json
Authorization: Bearer {{auth_token}}

> {% client.log("Change password page has a format: http://localhost:4200/#/reset-password/" + response.body["token"]) %}
###

PUT {{url}}/v1/user/reset-password
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzUxMiIsImlhdCI6MTYyOTgyMjEyOCwiZXhwIjoxNjMwNDI2OTI4LjB9.eyJ1c2VyX2lkIjo4fQ.ez1dKTjw8LdwJ7X-frrcjXEWt7WSq_ZpCfifcpxLjNQ_Q4P7WRBgLqGfw3f86xzpeO3GRed7OgjMxzc59Igonw",
  "password": "bag2r"
}

###

PUT {{url}}/v1/user/change-password
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "current_password": "",
  "new_password": ""
}


###
POST {{url}}/v1/txm-event/7/patients/recompute-parsing
Authorization: Bearer {{auth_token}}


###
POST {{url}}/v1/txm-event
Content-Type: application/json
Authorization: Bearer {{auth_token}}


{
  "name": "IKEM_TEST_EVENT_COPY_OF_01_2021"
}
