# test the api works

GET {{url}}/v1/service/version
Content-Type: application/json


# The workflow below has endpoints that add a user, change or reset password and call recompute endpoint
###

POST {{url}}/v1/user/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {% client.global.set("auth_token", response.body["auth_token"]); %}
###

POST {{url}}/v1/user/otp
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "otp": ""
}

> {% client.global.set("auth_token", response.body["auth_token"]); %}
###


POST {{url}}/v1/user/register
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "email": "",
  "password": "",
  "role": "ADMIN",
  "second_factor": "",
  "allowed_countries": [
    "AUT",
    "CZE",
    "ISR"
  ]
}
###

GET {{url}}/v1/user/request-reset/test
Content-Type: application/json

###

PUT {{url}}/v1/user/reset-password
Content-Type: application/json

{
  "token": "",
  "password": ""
}

###

PUT {{url}}/v1/user/change-password
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "current_password": "",
  "new_password": ""
}


###
POST {{url}}/v1/txm-event/7/patients/recompute-parsing
Authorization: Bearer {{auth_token}}


###
POST {{url}}/v1/txm-event
Content-Type: application/json
Authorization: Bearer {{auth_token}}


{
  "name": "IKEM_TEST_EVENT_COPY_OF_01_2021"
}
