# The workflow to change user password

GET {{url}}/v1/service/version
Content-Type: application/json

> {%
client.global.set("change_password_email", "demo@example.com");
client.global.set("new_password", "demo@example.com");
%}

### Registrer demo user

POST {{url}}/v1/user/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {% client.global.set("admin_auth_token", response.body["auth_token"]); %}

### Demo user is ready now, lets generate reset password link

GET {{url}}/v1/user/{{change_password_email}}/reset-password-token
Content-Type: application/json
Authorization: Bearer {{admin_auth_token}}

> {%
client.log("Change password page for " + client.global.get("change_password_email") + " has a format: " + client.global.get("url")+ "/#/reset-password/" + response.body["token"])
client.global.set("change_password_token", response.body["token"]);
 %}

###

PUT {{url}}/v1/user/reset-password
Content-Type: application/json

{
  "token": "{{change_password_token}}",
  "password": "{{new_password}}"
}
