GET {{url}}/v1/service/version


###
POST {{url}}/v1/user/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {% client.global.set("auth_token", response.body["auth_token"]); %}

###

POST {{url}}/v1/user/otp
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "otp": "718107"
}

> {% client.global.set("auth_token", response.body["auth_token"]); %}
###


POST {{url}}/v1/txm-event/2/export
Content-Type: application/json
Authorization: Bearer {{auth_token}}


{
  "country": "CZE",
  "new_txm_event_name": "test2"
}

>> tmp.json
###
POST {{url}}/v1/user/login
Content-Type: application/json

{
  "email": "{{service_username}}",
  "password": "{{service_password}}"
}

> {% client.global.set("auth_token", response.body["auth_token"]); %}

###
PUT {{url}}/v1/public/patient-upload
Authorization: Bearer {{auth_token}}
Content-Type: application/json

< /home/honza/Downloads/Austrian Data 012024/wien_export.json
