GET {{url}}/v1/service/version
Content-Type: application/json


###
POST {{url}}/v1/user/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {% client.global.set("auth_token", response.body["auth_token"]); %}

###


POST {{url}}/v1/user/otp
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "otp": "461389"
}

> {% client.global.set("auth_token", response.body["auth_token"]); %}
###

POST {{url}}/v1/txm-event/18/export
Content-Type: application/json
Authorization: Bearer {{auth_token}}


{
  "country": "BEL_2",
  "new_txm_event_name": "38-TXM-2022-07"
}


###
POST {{url}}/v1/user/login
Content-Type: application/json

{
  "email": "{{service_username}}",
  "password": "{{service_password}}"
}

> {% client.global.set("auth_token", response.body["auth_token"]); %}

###
PUT {{url}}/v1/public/patient-upload
Authorization: Bearer {{auth_token}}
Content-Type: application/json

< tmp.json
