GET https://txmatching.ikem.cz/v1/service/status
Content-Type: application/json

###

###

POST https://txmatching.ikem.cz/v1/user/login
Content-Type: application/json

{
  "email": "{{service_username}}",
  "password": "{{service_password}}"
}

> {% client.global.set("auth_token", response.body["auth_token"]); %}

###


PUT https://txmatching.ikem.cz/v1/public/patient-upload
Authorization: Bearer {{auth_token}}
Content-Type: application/json

# Here if you want to provide data in the file use the code below
< /path/to/data.json
# or i you want to provide the json directly use it as below
//{
//  "country": "AUT",
//  "txm_event_name": "test33",
//  "donors": [],
//  "recipients": []
//}
