POST {{url}}/v1/user/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {% client.global.set("auth_token", response.body["auth_token"]); %}


###
PUT {{url}}/v1/txm-event/8/patients/recipient
Content-Type: application/json
Authorization: Bearer {{auth_token}}

< update_patient_DB_ID.json