export enum AntibodyMatchType {
  NONE = "NONE",
  SPLIT = "SPLIT",
  BROAD = "BROAD",
  HIGH_RES = "HIGH_RES",
  UNDECIDABLE = "UNDECIDABLE",
  HIGH_RES_WITH_SPLIT = "HIGH_RES_WITH_SPLIT",
  HIGH_RES_WITH_BROAD = "HIGH_RES_WITH_BROAD",
  THEORETICAL = "THEORETICAL",
}
