TRUNCATE TABLE public.config RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.recipient RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.donor RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.pairing_result RESTART IDENTITY CASCADE;