name: Demo Deployment

env:
  AWS_ECR_REPOSITORY: demo-txm
  DEPLOYMENT_SERVICE: be

on:
  # manual dispatch
  workflow_dispatch:

jobs:
  build_server:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEMO_SSH_KEY }}
          known_hosts: ${{ secrets.DEMO_SSH_KNOWN_HOST }}

      - name: Redeploy application
        run: |
          ssh "${{ secrets.DEMO_SSH_CONNECTION }}" "cd /srv/service && ./redeploy.sh ${DEPLOYMENT_SERVICE}"
